//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bililive_dm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bililive_dm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非B站出品 ©2014-2019 CopyLiu 房间编号5051 问题反馈 copyliu@gmail.com.
        /// </summary>
        public static string ABout_Text {
            get {
                return ResourceManager.GetString("ABout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动重连.
        /// </summary>
        public static string AutoReconnect_Content {
            get {
                return ResourceManager.GetString("AutoReconnect.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开插件文件夹.
        /// </summary>
        public static string Btn_Text_OpenPluginDir {
            get {
                return ResourceManager.GetString("Btn_Text_OpenPluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还原默认.
        /// </summary>
        public static string Button_Content_Default {
            get {
                return ResourceManager.GetString("Button.Content.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试效果.
        /// </summary>
        public static string Button_Content_Text {
            get {
                return ResourceManager.GetString("Button.Content.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更换主题.
        /// </summary>
        public static string ChangeSkin {
            get {
                return ResourceManager.GetString("ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空投喂统计.
        /// </summary>
        public static string ClearMe_Content {
            get {
                return ResourceManager.GetString("ClearMe.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空弹幕统计.
        /// </summary>
        public static string ClearMe2_Content {
            get {
                return ResourceManager.GetString("ClearMe2.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空用户统计.
        /// </summary>
        public static string ClearMe3_Content {
            get {
                return ResourceManager.GetString("ClearMe3.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空弹幕统计(总).
        /// </summary>
        public static string ClearMe4_Content {
            get {
                return ResourceManager.GetString("ClearMe4.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接.
        /// </summary>
        public static string ConnBtn_Content {
            get {
                return ResourceManager.GetString("ConnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件名称.
        /// </summary>
        public static string DataGridTextColumn_Header_1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件名称.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件描述.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件作者.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件状态.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin4 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件版本.
        /// </summary>
        public static string DataGridTextColumn_Header_Plugin5 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header.Plugin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string DataGridTextColumn_Header1 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件描述.
        /// </summary>
        public static string DataGridTextColumn_Header2 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物品.
        /// </summary>
        public static string DataGridTextColumn_Header3 {
            get {
                return ResourceManager.GetString("DataGridTextColumn.Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断开.
        /// </summary>
        public static string DisconnBtn_Content {
            get {
                return ResourceManager.GetString("DisconnBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕姬窗口内容保存.
        /// </summary>
        public static string DisplayAffinity_Content {
            get {
                return ResourceManager.GetString("DisplayAffinity.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规则表达式过滤 符合规则表达式的弹幕将不会出现在任何地方直接丢弃.
        /// </summary>
        public static string EnableRegex_Content {
            get {
                return ResourceManager.GetString("EnableRegex.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可为空.
        /// </summary>
        public static string FontSizeValidationRule_Validate_不可为空 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不可为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是数字.
        /// </summary>
        public static string FontSizeValidationRule_Validate_不是数字 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_不是数字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须是正数.
        /// </summary>
        public static string FontSizeValidationRule_Validate_必须是正数 {
            get {
                return ResourceManager.GetString("FontSizeValidationRule_Validate_必须是正数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕.
        /// </summary>
        public static string Full_Content {
            get {
                return ResourceManager.GetString("Full.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屏蔽刷屏(α).
        /// </summary>
        public static string IgnoreSpam_Content {
            get {
                return ResourceManager.GetString("IgnoreSpam.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 观众互动.
        /// </summary>
        public static string Interact_Content {
            get {
                return ResourceManager.GetString("Interact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入了直播间.
        /// </summary>
        public static string InteractType_Text1 {
            get {
                return ResourceManager.GetString("InteractType_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关注了直播间.
        /// </summary>
        public static string InteractType_Text2 {
            get {
                return ResourceManager.GetString("InteractType_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享了直播间.
        /// </summary>
        public static string InteractType_Text3 {
            get {
                return ResourceManager.GetString("InteractType_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特别关注.
        /// </summary>
        public static string InteractType_Text4 {
            get {
                return ResourceManager.GetString("InteractType_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相互关注.
        /// </summary>
        public static string InteractType_Text5 {
            get {
                return ResourceManager.GetString("InteractType_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string InteractType_TextFormat {
            get {
                return ResourceManager.GetString("InteractType_TextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生了未知的互动事件.
        /// </summary>
        public static string InteractType_Unknown {
            get {
                return ResourceManager.GetString("InteractType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播间地址: http://live.bilibili.com/.
        /// </summary>
        public static string LiveRoomAddr {
            get {
                return ResourceManager.GetString("LiveRoomAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在自动重连....
        /// </summary>
        public static string MainWindow_b_Disconnected_正在自动重连___ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_正在自动重连___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接被断开.
        /// </summary>
        public static string MainWindow_b_Disconnected_连接被断开 {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_连接被断开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接被断开: 开发者信息{0}.
        /// </summary>
        public static string MainWindow_b_Disconnected_连接被断开__开发者信息_0_ {
            get {
                return ResourceManager.GetString("MainWindow_b_Disconnected_连接被断开__开发者信息_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播间人数：{0}.
        /// </summary>
        public static string MainWindow_b_ReceivedRoomCount_ {
            get {
                return ResourceManager.GetString("MainWindow_b_ReceivedRoomCount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前房间人数:{0}.
        /// </summary>
        public static string MainWindow_b_ReceivedRoomCount_当前房间人数__0_ {
            get {
                return ResourceManager.GetString("MainWindow_b_ReceivedRoomCount_当前房间人数__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接房间号：{0}.
        /// </summary>
        public static string MainWindow_connbtn_Click_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID不合法.
        /// </summary>
        public static string MainWindow_connbtn_Click_ID非法 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_ID非法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错信息：{0}.
        /// </summary>
        public static string MainWindow_connbtn_Click_出错 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕姬报告.
        /// </summary>
        public static string MainWindow_connbtn_Click_弹幕姬本身 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_弹幕姬本身", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接.
        /// </summary>
        public static string MainWindow_connbtn_Click_正在连接 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_正在连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入房间编码,房间编码是!数!字!.
        /// </summary>
        public static string MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_ {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_请输入房间号_房间号是_数_字_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接失败.
        /// </summary>
        public static string MainWindow_connbtn_Click_连接失败 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接成功.
        /// </summary>
        public static string MainWindow_connbtn_Click_连接成功 {
            get {
                return ResourceManager.GetString("MainWindow_connbtn_Click_连接成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *Debug模式*.
        /// </summary>
        public static string MainWindow_MainWindow_____Debug模式_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____Debug模式_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *弱智版本*.
        /// </summary>
        public static string MainWindow_MainWindow_____傻逼版本_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____傻逼版本_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   *原始数据输出*.
        /// </summary>
        public static string MainWindow_MainWindow_____原始数据输出_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_____原始数据输出_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   版本号:.
        /// </summary>
        public static string MainWindow_MainWindow____版本号__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____版本号__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   编译时间:.
        /// </summary>
        public static string MainWindow_MainWindow____编译时间__ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow____编译时间__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请有空发给联系方式 {0} 谢谢.
        /// </summary>
        public static string MainWindow_MainWindow_Closed_报错 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_报错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件{0}遇到了不明错误: 日志已经保存在桌面, 请有空发给该插件作者 {1}, 联系方式 {2}.
        /// </summary>
        public static string MainWindow_MainWindow_Closed_插件错误 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Closed_插件错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕姬决定下版本开始停止支持Windows XP, 最低要求更改至 Win7 和 .NET 4.6.1,为保证你能在今后使用弹幕姬, 请安装最新的 .net framework ..
        /// </summary>
        public static string MainWindow_MainWindow_NetError {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_NetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的打开方式不正确.
        /// </summary>
        public static string MainWindow_MainWindow_你的打开方式不正确 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_你的打开方式不正确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告1: 由于廉价的证书供应商被某虎公司搞死了于是没钱买证书了, 所以使用本软件时可能会跳安全提示请无需理会..
        /// </summary>
        public static string MainWindow_MainWindow_公告1 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告2: 最近出现了一些所谓弹幕姬后续版, 声称本软件已经不再更新, 并自称后续版是原作者开发是新版云云..
        /// </summary>
        public static string MainWindow_MainWindow_公告2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对此进行澄清, 弹幕姬从来也不会有任何的所谓后续版, 原作者直播间ID是5051, 任何非本人所开发的软件的一切问题均不能解答..
        /// </summary>
        public static string MainWindow_MainWindow_公告2_2 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 也请用户在咨询时, 确认清楚你所使用的软件类型, 向正确的关系者咨询. 谢谢..
        /// </summary>
        public static string MainWindow_MainWindow_公告2_3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告3: 投喂记录不会在弹幕模式上出现, 这不是bug.
        /// </summary>
        public static string MainWindow_MainWindow_公告3 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_公告3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以点击日志拷贝到剪贴板.
        /// </summary>
        public static string MainWindow_MainWindow_可以点击日志复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_可以点击日志复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前为Debug模式.
        /// </summary>
        public static string MainWindow_MainWindow_当前为Debug模式 {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_当前为Debug模式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开插件文件夹出错
        ///信息.
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_ {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开插件文件夹出错.
        /// </summary>
        public static string MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错 {
            get {
                return ResourceManager.GetString("MainWindow_OpenPluginFolder_OnClick_打开插件文件夹出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件{0}遇到了不明错误: 日志已经保存在桌面, 请有空发给该插件作者 {1}, 联系方式 {2}.
        /// </summary>
        public static string MainWindow_Plugin_Disable_插件报错2 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Disable_插件报错2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件{0}遇到了不明错误: 日志已经保存在桌面, 请有空发给该插件作者 {1}, 联系方式 {2}.
        /// </summary>
        public static string MainWindow_Plugin_Enable_插件报错 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_插件报错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请有空发给联系方式 {0} 谢谢.
        /// </summary>
        public static string MainWindow_Plugin_Enable_请有空发给联系方式__0__谢谢 {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Enable_请有空发给联系方式__0__谢谢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!SuperChat!!!.
        /// </summary>
        public static string MainWindow_ProcDanmaku____SuperChat___ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku____SuperChat___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 购买了 {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 赠送的: {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [爷].
        /// </summary>
        public static string MainWindow_ProcDanmaku__VIP前缀 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__VIP前缀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [管].
        /// </summary>
        public static string MainWindow_ProcDanmaku__管理员前缀_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__管理员前缀_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入直播间.
        /// </summary>
        public static string MainWindow_ProcDanmaku__进入直播间 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku__进入直播间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上船.
        /// </summary>
        public static string MainWindow_ProcDanmaku_上船 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_上船", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上船:{0} 购买了 {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_上船__0__购买了__1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 和管理.
        /// </summary>
        public static string MainWindow_ProcDanmaku_和管理 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_和管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总督.
        /// </summary>
        public static string MainWindow_ProcDanmaku_总督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_总督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督.
        /// </summary>
        public static string MainWindow_ProcDanmaku_提督 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_提督", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到弹幕:{0}{1}{2} 说: {3}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到弹幕__0__1__2__说___3_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到弹幕__0__1__2__说___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到道具.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收到道具:{0} 赠送的: {1} x {2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_收到道具__0__赠送的___1__x__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎{0}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎_0_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎{0}: {1}{2}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎_0____1__2_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎_0____1__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎老爷{0}.
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎老爷_0_ {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎老爷_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎老爷{0}: {1} 进入直播间.
        /// </summary>
        public static string MainWindow_ProcDanmaku_欢迎老爷_0____1__进入直播间 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_欢迎老爷_0____1__进入直播间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 舰长.
        /// </summary>
        public static string MainWindow_ProcDanmaku_舰长 {
            get {
                return ResourceManager.GetString("MainWindow_ProcDanmaku_舰长", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕姬测试.
        /// </summary>
        public static string MainWindow_Test_OnClick_弹幕姬测试 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_弹幕姬测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件弹幕测试.
        /// </summary>
        public static string MainWindow_Test_OnClick_插件弹幕测试 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_插件弹幕测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这不是个测试.
        /// </summary>
        public static string MainWindow_Test_OnClick_这不是个测试 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_这不是个测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这是一个测试.
        /// </summary>
        public static string MainWindow_Test_OnClick_这是一个测试 {
            get {
                return ResourceManager.GetString("MainWindow_Test_OnClick_这是一个测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本行记录已拷贝到剪贴板.
        /// </summary>
        public static string MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板 {
            get {
                return ResourceManager.GetString("MainWindow_UIElement_OnMouseLeftButtonUp_本行记录已复制到剪贴板", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        public static string MenuItem_Header_PluginAdmin {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活插件.
        /// </summary>
        public static string MenuItem_Header_PluginEnabvle {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginEnabvle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停用插件.
        /// </summary>
        public static string MenuItem_Header_PluginStop {
            get {
                return ResourceManager.GetString("MenuItem.Header.PluginStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投喂榜.
        /// </summary>
        public static string RankTabItem_Header {
            get {
                return ResourceManager.GetString("RankTabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存日志.
        /// </summary>
        public static string SaveLog_Content {
            get {
                return ResourceManager.GetString("SaveLog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕模式使用.
        /// </summary>
        public static string ScreenSelecter {
            get {
                return ResourceManager.GetString("ScreenSelecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示出错信息.
        /// </summary>
        public static string ShowError_Content {
            get {
                return ResourceManager.GetString("ShowError.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 道具老爷.
        /// </summary>
        public static string ShowItem_Content {
            get {
                return ResourceManager.GetString("ShowItem.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧边栏.
        /// </summary>
        public static string SideBar_Content {
            get {
                return ResourceManager.GetString("SideBar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题选择器.
        /// </summary>
        public static string SkinSelector {
            get {
                return ResourceManager.GetString("SkinSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伪春菜联动.
        /// </summary>
        public static string SSTP_Content {
            get {
                return ResourceManager.GetString("SSTP.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 醒目留言:{0}{1}{2} 说: {3}.
        /// </summary>
        public static string SuperChatLogName {
            get {
                return ResourceManager.GetString("SuperChatLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string TabItem_Header {
            get {
                return ResourceManager.GetString("TabItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件.
        /// </summary>
        public static string TabItem_Header_Plugin {
            get {
                return ResourceManager.GetString("TabItem.Header.Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string TabItem_Header_Setting {
            get {
                return ResourceManager.GetString("TabItem.Header.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 说明.
        /// </summary>
        public static string TabItem_Header_Web {
            get {
                return ResourceManager.GetString("TabItem.Header.Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试效果.
        /// </summary>
        public static string Test_Content {
            get {
                return ResourceManager.GetString("Test.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前人气值:.
        /// </summary>
        public static string TextBlock_Text {
            get {
                return ResourceManager.GetString("TextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意: 新弹幕引擎下文本速度选项无效.
        /// </summary>
        public static string TextBlock_Text_EnableNewEngineWarn {
            get {
                return ResourceManager.GetString("TextBlock.Text.EnableNewEngineWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕模式文本速度.
        /// </summary>
        public static string TextBlock_Text_FSpeed {
            get {
                return ResourceManager.GetString("TextBlock.Text.FSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕模式文本大小.
        /// </summary>
        public static string TextBlock_Text_FTextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.FTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件目录: 我的文档\弹幕姬\Plugins.
        /// </summary>
        public static string TextBlock_Text_PluginDir {
            get {
                return ResourceManager.GetString("TextBlock.Text.PluginDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总共收到弹幕(原始数据).
        /// </summary>
        public static string TextBlock_Text_R1 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总共收到弹幕(已显示).
        /// </summary>
        public static string TextBlock_Text_R2 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参与评论的用户.
        /// </summary>
        public static string TextBlock_Text_R3 {
            get {
                return ResourceManager.GetString("TextBlock.Text.R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示文本出现时长.
        /// </summary>
        public static string TextBlock_Text_SEff2Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff2Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示文本消失时长.
        /// </summary>
        public static string TextBlock_Text_SEff3Time {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEff3Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示出现时拉伸时长.
        /// </summary>
        public static string TextBlock_Text_SEffTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SEffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示文本停留时长.
        /// </summary>
        public static string TextBlock_Text_SKeepTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SKeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示出现时拉伸时长.
        /// </summary>
        public static string TextBlock_Text_SShowTime {
            get {
                return ResourceManager.GetString("TextBlock.Text.SShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧提示文本字体大小.
        /// </summary>
        public static string TextBlock_Text_STextSize {
            get {
                return ResourceManager.GetString("TextBlock.Text.STextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧窗口宽度.
        /// </summary>
        public static string TextBlock_Text_SWidth {
            get {
                return ResourceManager.GetString("TextBlock.Text.SWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧窗口X偏移.
        /// </summary>
        public static string TextBlock_Text_SXOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SXOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侧窗口Y偏移.
        /// </summary>
        public static string TextBlock_Text_SYOffset {
            get {
                return ResourceManager.GetString("TextBlock.Text.SYOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口置顶.
        /// </summary>
        public static string WindowTop_Content {
            get {
                return ResourceManager.GetString("WindowTop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹幕模式使用新弹幕引擎(Windows 8 以上).
        /// </summary>
        public static string WTFEngineEnable_Content {
            get {
                return ResourceManager.GetString("WTFEngineEnable.Content", resourceCulture);
            }
        }
    }
}
